### ISSUE TITLE
Couldn't parse bio: java.text.ParseException: Unparseable date: "May 6, 1990"

### ISSUE THREAD

**Issue by cristianocaeiro** [lamarios/sherdog-parser#14]
Hi,
first of all thank you for creating this awesome project. Even after your update to 2.14 to support the new sherdog ui, there are some things that don't work. When parsing fighter bios the date can't be parsed:

```
2022-01-20 13:32:37.947  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Refreshing fighter https://www.sherdog.com/fighter/Francis-Ngannou-152341
2022-01-20 13:32:37.951  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Found 1 fight history tables
2022-01-20 13:32:37.951  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : 20 TRs to parse through
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC 260 - Miocic vs. Ngannou 2', sherdogUrl='https://www.sherdog.com/events/UFC-260-Miocic-vs-Ngannou-2-88377'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Stipe Miocic', sherdogUrl='https://www.sherdog.com/fighter/Stipe-Miocic-39537'}, date=2021-03-27T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='KO (Punch)', winTime='0:52', winRound=2}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC 249 - Ferguson vs. Gaethje', sherdogUrl='https://www.sherdog.com/events/UFC-249-Ferguson-vs-Gaethje-84357'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Jairzinho Rozenstruik', sherdogUrl='https://www.sherdog.com/fighter/Jairzinho-Rozenstruik-102803'}, date=2020-05-09T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='KO (Punches)', winTime='0:20', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC on ESPN 3 - Ngannou vs. Dos Santos', sherdogUrl='https://www.sherdog.com/events/UFC-on-ESPN-3-Ngannou-vs-Dos-Santos-73351'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Junior dos Santos', sherdogUrl='https://www.sherdog.com/fighter/Junior-dos-Santos-17272'}, date=2019-06-29T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='TKO (Punches)', winTime='1:11', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC on ESPN 1 - Ngannou vs. Velasquez', sherdogUrl='https://www.sherdog.com/events/UFC-on-ESPN-1-Ngannou-vs-Velasquez-72025'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Cain Velasquez', sherdogUrl='https://www.sherdog.com/fighter/Cain-Velasquez-19102'}, date=2019-02-17T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='KO (Punches)', winTime='0:26', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC Fight Night 141 - Blaydes vs. Ngannou 2', sherdogUrl='https://www.sherdog.com/events/UFC-Fight-Night-141-Blaydes-vs-Ngannou-2-69287'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Curtis Blaydes', sherdogUrl='https://www.sherdog.com/fighter/Curtis-Blaydes-172939'}, date=2018-11-24T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='TKO (Punches)', winTime='0:45', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC 226 - Miocic vs. Cormier', sherdogUrl='https://www.sherdog.com/events/UFC-226-Miocic-vs-Cormier-65367'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Derrick Lewis', sherdogUrl='https://www.sherdog.com/fighter/Derrick-Lewis-59284'}, date=2018-07-07T00:00+02:00[Europe/Berlin], result=FIGHTER_2_WIN, winMethod='Decision (Unanimous)', winTime='5:00', winRound=3}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC 220 - Miocic vs. Ngannou', sherdogUrl='https://www.sherdog.com/events/UFC-220-Miocic-vs-Ngannou-63763'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Stipe Miocic', sherdogUrl='https://www.sherdog.com/fighter/Stipe-Miocic-39537'}, date=2018-01-20T00:00+01:00[Europe/Berlin], result=FIGHTER_2_WIN, winMethod='Decision (Unanimous)', winTime='5:00', winRound=5}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC 218 - Holloway vs. Aldo 2', sherdogUrl='https://www.sherdog.com/events/UFC-218-Holloway-vs-Aldo-2-61991'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Alistair Overeem', sherdogUrl='https://www.sherdog.com/fighter/Alistair-Overeem-461'}, date=2017-12-02T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='KO (Punch)', winTime='1:42', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC on Fox 23 - Shevchenko vs. Pena', sherdogUrl='https://www.sherdog.com/events/UFC-on-Fox-23-Shevchenko-vs-Pena-56245'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Andrei Arlovski', sherdogUrl='https://www.sherdog.com/fighter/Andrei-Arlovski-270'}, date=2017-01-28T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='TKO (Punches)', winTime='1:32', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC Fight Night 102 - Lewis vs. Abdurakhimov', sherdogUrl='https://www.sherdog.com/events/UFC-Fight-Night-102-Lewis-vs-Abdurakhimov-54999'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Anthony Hamilton', sherdogUrl='https://www.sherdog.com/fighter/Anthony-Hamilton-58947'}, date=2016-12-09T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='Submission (Kimura)', winTime='1:57', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC on Fox 20 - Holm vs. Shevchenko', sherdogUrl='https://www.sherdog.com/events/UFC-on-Fox-20-Holm-vs-Shevchenko-51563'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Bojan Mihajlovic', sherdogUrl='https://www.sherdog.com/fighter/Bojan-Mihajlovic-12400'}, date=2016-07-23T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='TKO (Punches)', winTime='1:34', winRound=1}
2022-01-20 13:32:37.952  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC Fight Night 86 - Rothwell vs. Dos Santos', sherdogUrl='https://www.sherdog.com/events/UFC-Fight-Night-86-Rothwell-vs-Dos-Santos-50295'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Curtis Blaydes', sherdogUrl='https://www.sherdog.com/fighter/Curtis-Blaydes-172939'}, date=2016-04-10T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='TKO (Doctor Stoppage)', winTime='5:00', winRound=2}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='UFC on Fox 17 - Dos Anjos vs. Cerrone 2', sherdogUrl='https://www.sherdog.com/events/UFC-on-Fox-17-Dos-Anjos-vs-Cerrone-2-42249'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Luis Henrique Barbosa de Oliveira', sherdogUrl='https://www.sherdog.com/fighter/Luis-Henrique-Barbosa-de-Oliveira-6608'}, date=2015-12-19T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='KO (Punch)', winTime='2:53', winRound=2}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='KHK MMA National Tryouts - Finale 2015', sherdogUrl='https://www.sherdog.com/events/KHK-MMA-National-Tryouts-Finale-2015-47105'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='William Baldutti', sherdogUrl='https://www.sherdog.com/fighter/William-Baldutti-71441'}, date=2015-05-28T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='TKO (Punches)', winTime='N/A', winRound=2}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='SHC 10 - Carvalho vs. Belo', sherdogUrl='https://www.sherdog.com/events/SHC-10-Carvalho-vs-Belo-39271'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Luc Ngeleka', sherdogUrl='https://www.sherdog.com/fighter/Luc-Ngeleka-167427'}, date=2014-09-20T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='Submission (Guillotine Choke)', winTime='0:43', winRound=1}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='100% Fight 20 - Comeback', sherdogUrl='https://www.sherdog.com/events/10037-Fight-20-Comeback-37143'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Nicolas Specq', sherdogUrl='https://www.sherdog.com/fighter/Nicolas-Specq-159689'}, date=2014-04-05T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='Submission (Arm-Triangle Choke)', winTime='2:10', winRound=2}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='100% Fight 20 - Comeback', sherdogUrl='https://www.sherdog.com/events/10037-Fight-20-Comeback-37143'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Bilal Tahtahi', sherdogUrl='https://www.sherdog.com/fighter/Bilal-Tahtahi-164175'}, date=2014-04-05T00:00+02:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='KO (Punch)', winTime='3:58', winRound=1}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='100% Fight - Contenders 21', sherdogUrl='https://www.sherdog.com/events/10037-Fight-Contenders-21-34421'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Zoumana Cisse', sherdogUrl='https://www.sherdog.com/fighter/Zoumana-Cisse-126463'}, date=2013-12-14T00:00+01:00[Europe/Berlin], result=FIGHTER_2_WIN, winMethod='Decision (Unanimous)', winTime='5:00', winRound=2}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Fight{event=SherdogBaseObject{name='100% Fight - Contenders 20', sherdogUrl='https://www.sherdog.com/events/10037-Fight-Contenders-20-33415'}, fighter1=SherdogBaseObject{name='Francis Ngannou', sherdogUrl='https://www.sherdog.com/fighter/Francis-Ngannou-152341'}, fighter2=SherdogBaseObject{name='Rachid Benzina', sherdogUrl='https://www.sherdog.com/fighter/Rachid-Benzina-152343'}, date=2013-11-30T00:00+01:00[Europe/Berlin], result=FIGHTER_1_WIN, winMethod='Submission (Armbar)', winTime='1:44', winRound=1}
2022-01-20 13:32:37.953  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Found 20 fights for Francis Ngannou
2022-01-20 13:32:38.175  INFO 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Refreshing fighter https://www.sherdog.com/fighter/Ciryl-Gane-293973
2022-01-20 13:32:38.176 ERROR 72911 --- [nio-8080-exec-3] c.f.sherdogparser.parsers.FighterParser  : Couldn't parse bio

java.text.ParseException: Unparseable date: "May 6, 1990"
	at java.base/java.text.DateFormat.parse(DateFormat.java:395) ~[na:na]
	at com.ftpix.sherdogparser.parsers.FighterParser.parseDocument(FighterParser.java:113) ~[sherdog-parser-2.14.jar:na]
	at com.ftpix.sherdogparser.parsers.FighterParser.parseDocument(FighterParser.java:31) ~[sherdog-parser-2.14.jar:na]
	at com.ftpix.sherdogparser.parsers.SherdogParser.parse(SherdogParser.java:35) ~[sherdog-parser-2.14.jar:na]
	at com.ftpix.sherdogparser.Sherdog.getFighter(Sherdog.java:141) ~[sherdog-parser-2.14.jar:na]
---
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
---
---
---
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
---
---
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by lamarios** [comment]
Yeah. I realized there are still issues. I'll need to have a look at it when I have some free time (which might not be so soon)

**Comment by cristianocaeiro** [comment]
@lamarios I made some fixes but could not push my branch (permission denied)... Can your give me permission ?

**Comment by lamarios** [comment]
Oh. You need to make a fork of the project then you can make a PR

**Comment by cristianocaeiro** [comment]
Done. Could you take a look at it ?

**Comment by cristianocaeiro** [comment]
@lamarios when will the new version be available on maven central ?

**Comment by lamarios** [comment]
I just published it, it might take a short while to be available on maven central. Thanks for your help !
